### ISSUE TITLE
Errno2

### ISSUE THREAD

**Issue by timelij** [trustedsec/social-engineer-toolkit#302]
Hey

Always when Im trying to use the "Arduino-Based Attack Vector" and use a payload,I encounter alwasy the same problem "[Errno 2] No such file or directory: 'src/teensypowershell_down.pde" or "[Errno 2] No such file or directory: '/root/.set/x86.powershell/w".
Am I doing something wrong ?
 Running: Kali Linux

**Comment by Paraphe** [comment]
I have the same issue here. Seems like SET forget the "/" between teensy and powershell_down.pde.
It should be >  src/teensy**/**powershell_down.pde. 
I went to the setcore.py file, and the paths were ok. So, I don't know where the problem comes from.

**Comment by Paraphe** [comment]
Oh, I finally found how to fix it !
Go in usr/share/set/src/teensy/, open teensy.py, and at the line 86  
with open(os.path.join("src/teensy" + filename)) as fileopen, \,

just add "/" after teensy. 

So it will be : 
with open(os.path.join("src/teensy**/**" + filename)) as fileopen, \,

and it will fix it.

@trustedsec You should fix it in a next update, it's not especially obvious :)

**Comment by NovaHowl** [comment]
@trustedsec Still having the problem after I changed the line.

[!] Something went wrong, printing the error: [Errno 2] No such file or directory: '/root/.set/x86.powershell/w'
